### ISSUE TITLE
Unable to peer with bot collaboration client

### ISSUE THREAD

**Issue by ssinghxyz** [SpectrumCollaborationChallenge/phase2-hurdle#16] opened 2018-04-25 19:27 UTC
Hello,

We are unable to peer with the bot's collaboration gateway. When we register with the collaboration server, we only see our own ID in the "neighbours" field, in the "notify" message from the collaboration server.

We investigated the logs of the collaboration server - this is attached 
[collab_server.log](https://github.com/SpectrumCollaborationChallenge/phase2-hurdle/files/1948527/collab_server.log)

The logs show that, at timestamp 1524682827, the collaboration server receives "register" message from the bot's collaboration client. At timestamp, 1524683172, the collaboration server receives "register" message from the competitor's (our) collaboration client. As can be seen, in the "notify" and "inform" message sent to our client at the same timestamp 1524683172, the list of neighbours only includes the competitor collaboration client, and does not include the bot's collaboration client.

Further, the collaboration server also logs some errors, e.g. "1524682906 - collab_server.py:389 - ERROR - received invalid message type 392976821"

Are we doing something incorrect ?

**Comment by craig-pomeroy** [comment] 2018-04-26 14:55
We've looked at your logs and are going to try to reproduce the issue on our side. Please stand by.

**Comment by ssinghxyz** [comment] 2018-04-26 17:58
Thank you.
I ran the test with --container-boot-timeout=30, I observed the same behaviour. The collaboration server logs are attached 
[collab_server.log](https://github.com/SpectrumCollaborationChallenge/phase2-hurdle/files/1952372/collab_server.log)
The server started at time instant 1524764492, the bot registered with the server at 1524764530, our competitor client registered at 1524764770. The inform message received by the competitor at instant 1524764770 only showed one neighbour, which is the competitor itself.
Is there anything else that we may be doing wrong ?

**Comment by craig-pomeroy** [comment] 2018-04-27 22:09
It looks like you've found a race condition in the container boot process. It looks like there's a simple fix. Stand by.

**Comment by ssinghxyz** [comment] 2018-04-30 15:54
Thank you ! We are able to peer with the bot's collaboration client now.

**Comment by craig-pomeroy** [comment] 2018-04-30 17:59
Great! We'll close this issue.

**Closed by craig-pomeroy** 2018-04-30 17:59 UTC
